version: '3.8'

services:
# vite/react application container
  client:
    container_name: vite
    image: react
    build:
      context: .
      dockerfile: client.Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - pine
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}

# database container
  db:
    container_name: database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    networks:
      - pine
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/mysql
      - ./database/sql:/docker-entrypoint-initdb.d

# expressServer container
  server:
    image: express
    container_name: server
    build:
      context: .
      dockerfile: server.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - pine
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

volumes:
  db_data:

networks:
  pine:
    driver: bridge